### ISSUE TITLE
Improve datarange

### ISSUE THREAD

**Issue by nithinmurali** [nithinmurali/pygsheets#276]
Improve datarange and protected range

**Comment by Kordishal** [comment]
I have been thinking about this as well.

I think overall it would be better to take the DataRange class apart into several classes which inherit from each other.

You can see my current progress [here](https://github.com/Kordishal/pygsheets/blob/feature/refactor-datarange/pygsheets/datarange.py)

A few notes:
- The Address object is supposed to replace the format_addr utility function and acts as the base building block for ranges. As object it can act both as label and coordinate tuple. Overwriting the __eq__ and __ne__ allows for comparison between two addresses. And there are some sanity checks in there whether the coordinates can make sense.
- The Range class ist the base class for all ranges. It just offers a start and end value. __str__ returns the range in A1 notation.
- The GridRange class is connected to a worksheet and as such is aware of where it belongs. And offers a convience function to get the gridrange object for the API. It subclasses Range.
- The ValueRange contains all the plain values. With the added benefit, that all the values can be loaded and stored easily. This should make it clear how to work with this. Can even change major dimension. However otherwise there are not too many sanity checks when changing things around.
- The DataRange is still mostly as it was. This should be reworked to a CellDataRange or just CellRange. It would just offer the same API as the ValueRange, but contain cells instead of values.
- The NamedRange is a subclass of CellRange and adds functions for names etc.
- The ProtectedRange is a subclass of CellRange as well and adds utility functions.

It would be possible to add a similar class like ValueRange named DictRange which contains values as ordered dict with the first row or column as the dict keys.

I haven't really invested much recently as it would be again a major change... like 3.0 release ;)

The only thing we could do is keep the DataRange around and add the other ranges as additions.

The only question would be how to deal with functions that currently return DataRanges.

**Comment by Kordishal** [comment]
But as a side note:

The ValueRange, GridRange, Range & Address classes could be added without changes to the API. So I could work on that.

**Comment by nithinmurali** [comment]
Separating the Datarange into value range is useful. But about other ranges, i think you might be over-engineering a bit.  you could combine the Range and Gridrange rt? both are serving as base classes only.  The address is also useful, but if we ask the users to input all the cell addresses as this `Address object, it might be inconvenient.

> The only question would be how to deal with functions that currently return DataRanges.

That we can add more options like 'valueRange', 'CellRange' etc. and default 'range' to CellRange

**Comment by nithinmurali** [comment]
Also i am not really sure how many ppl use these ranges, as i have seen very few issues raised on ranges even-though they are very buggy. That is a reason why i hacked a 'not so good' solution to fix the trivial issues.

**Comment by Kordishal** [comment]
We could do that.

The Address object could be used for internals only as it simplifies some internal code, but people can input labels, coordinates or Address objects.

As for not used much: Could also be because they are not working very good ;)

And at least the ValueRange is something I would use. The goal of ValueRange is to give easy access to values in a sheet. I feel this is currently somewhat missing.

And for the NamedRange & ProtectedRange extractions I honestly couldn't fully finish yet. And there is still much to do, so I will probably not finish it.

**Comment by Kordishal** [comment]
The idea behind having separate classes for Range and GridRange is, that you can just call str on them and get the desired values. But this could be of course solved by adding grid_range, range properties.

**Comment by nithinmurali** [comment]
> As for not used much: Could also be because they are not working very good ;)

:smiley:  Possible

The ValueRange and Adress can be really useful. You can maybe make a PR just with that for the time being.

**Comment by karaluh** [comment]
Also, protected ranges lack the option to access and set description. Should I file a new feature request for this?

**Comment by nithinmurali** [comment]
@karaluh Yeah please create a separate issue for that. This issue is about complete refactoring or `ranges`, description can probably be Incorporated with the current model without much work. 

Current way of handling address is giving a lot of issues. So I will probably work on the refactoring this weekend.

**Comment by nithinmurali** [comment]
Implemented a redacted version of grid-range and Address from @Kordishal 's implementation. This solves many issues in Datarange. So closing this issue for now.
