### ISSUE TITLE
sh_batch_update removed from client

### ISSUE THREAD

**Issue by luciusb** [nithinmurali/pygsheets#304]
Note, if this is a usage question, please ask a question in stackoverflow with `pygsheets` tag.

**Describe the bug**
custom_request is not working because sh_batch_update is not in client.py

**To Reproduce**
Any call to custom_request will fail

**System Information**
 - OS: linux, windows
 - pygsheets version : 2.0
 - pygsheets installed from (github or pypi): github

**Comment by Djones4822** [comment]
Hi, this issue isn't pushed to the master.zip file that you provide as the download link in your ReadMe. I haven't tried PyPI, though. could you please update that when you get a chance? 

Thank you,
David

**Comment by nithinmurali** [comment]
Sorry i missed that. Done in #316.

**Comment by Unprocessable** [comment]
The old version is still on PyPi, I noticed while trying to do a request. I was actually in the process of fixing the bug and submitting it, only to find that the bug was already fixed.

For those of you still using the older version: pgsheet.client.sheet.batch_update(<request>) will work just fine if pgsheet is an instance of 'pygsheets.spreadsheet.Spreadsheet' or 'pygsheets.worksheet.Worksheet'.
