### ISSUE TITLE
Programmatically write conditional formatting

### ISSUE THREAD

**Issue by themcclure** [nithinmurali/pygsheets#426]
I have a problem where there are many versions of my spreadsheet out in the wild being used for data entry by people outside of my control. 
To aid them in their data entry, one of the sheets has a lot of conditional formatting to highlight errors and such.
Sometimes when people paste in data or insert new rows, the conditional formatting rules are no longer present for the new rows. (range becomes, for example B2:B3,B5,B7:B1005 rather than B2:B).

I am looking for a library call where I can load a fresh set of conditional rules from my template and  remotely refresh all the active spreadsheets. I use pygsheets to make lots of other updates from the template but I am currently unable to do this last piece.

Rather than making a direct (non library based) call to the API directly (https://developers.google.com/sheets/api/samples/conditional-formatting) it would be good if there was a library call that would let me do that.

Thanks

**Comment by nithinmurali** [comment]
At the moment conditional formatting is not supported by models. But rather than doing raw api call, you can use [custom_request](https://pygsheets.readthedocs.io/en/latest/spreadsheet.html#pygsheets.Spreadsheet.custom_request) to make api calls which are not yet available in models. 

also note that for getting the range in json ([Grid range](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/other#GridRange) format required by api)  you can use  worksheet GridRange model. `GridRange(worksheet=wks, start='A1', end='D4').to_json()`.
