### ISSUE TITLE
Support current python versions

### ISSUE THREAD

**Issue by dankrause** [nithinmurali/pygsheets#465]
https://github.com/nithinmurali/pygsheets/blob/8f4a7f18abc621add54a7b9fe52e7a3911726cd0/.travis.yml#L2-L6

I suggest removing support for Python 2.7, 3.4, and 3.5, as these Python releases are EOL. I suggest adding support for Python 3.7, 3.8, and 3.9.

**Comment by dankrause** [comment]
See: https://devguide.python.org/#status-of-python-branches

**Comment by nithinmurali** [comment]
We can remove support for 3.4 and 3.5. But regarding 2.7 i am a bit skeptical. Since this was an LTS release there might be a lot of code who hasn't still migrated to 3.x .  (Even at our workplace we are still migrating to 3.x). 

So I would suggest lets wait an year or so before we remove 2.x support. For now lets remove 3.4 and 3.5 and add 3.7, 3.8 and 3.9

**Comment by nithinmurali** [comment]
Lets do this. Create a separate PR for dropping python 2.7. We will merge it in next major release.
