### ISSUE TITLE
Instantiating/ uploading worksheet

### ISSUE THREAD

**Issue by kc1** [nithinmurali/pygsheets#51]
Please see http://stackoverflow.com/questions/42352185/how-to-upload-a-worksheet-using-pygsheets

Thank you very much for the project!

**Comment by nithinmurali** [comment]
The `JsonSheet`  param is not for setting data on the worksheet, it is for specifying the properties of the worksheet , hence should be of [this](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets#Sheet) format. 

As directly converting a json to spreadsheet is rather ambiguous, you will need to first convert it to a numpy array (matrix) or an pandas DataFrame. Then you can use `set_as_df` of just `update_values` for updating the spreadsheet.

Also If you could use `pygsheets` tag in stack-overflow, so that we can directly get notified on any question.
