### ISSUE TITLE
set_text_format and set_text_rotation are not working

### ISSUE THREAD

**Issue by abdoukarim** [nithinmurali/pygsheets#76]
I just found an issue when using set_text_format and set_text_rotation on a cell instance.
I got this error: `'NoneType' object has no attribute 'value'`
Removing .value [here](https://github.com/nithinmurali/pygsheets/blob/master/pygsheets/cell.py#L281) solves this issue.

**Comment by nithinmurali** [comment]
Can you see what is the value of the `format` ? just after the cell is created, and before you call set_text_rotation.

**Comment by abdoukarim** [comment]
the value of `format` is `(None, '')` when the cell is created like this `cell.value="My cell value"`

**Comment by nithinmurali** [comment]
What is your python version and OS?

**Comment by abdoukarim** [comment]
Python 2.7.10 and & Mac OS X

**Comment by nithinmurali** [comment]
try this `cell.format = pygsheets.FormatType.CUSTOM` before calling `cell.set_text_format` does it work? also what is the value of  `cell.format` now?

**Comment by abdoukarim** [comment]
it still doesn't work cell.format will still have a `None` value which will result to the same error.

**Comment by abdoukarim** [comment]
We can also use `getattr function` `getattr(nformat, 'value', nformat)` to solve it.

**Comment by nithinmurali** [comment]
Right, that will work. Though I still cant figure out why enums are converted to their values in your case.

**Comment by nithinmurali** [comment]
Ahh, I got it, its interpreter dependent. I am using anaconda python, that's why. Thanks for reporting this !! I will fix them.

**Comment by psdantonio** [comment]
> I just found an issue when using set_text_format and set_text_rotation on a cell instance. I got this error: 'NoneType' object has no attribute 'value' Removing .value here solves this issue.

just wanted to add that i currently have the same issue w/ python 2.7 on win10. the same error message pops up with any attempt to change the format of a cell (text format or cell color, etc.). while removing '.value' from cell.py allows the code to execute, the result on my google sheet is rather buggy (it'll claim that the text is formatted but won't be unless one double clicks on a cell.)

**Comment by nithinmurali** [comment]
Hi @psdantonio  , where did you change the `.value`? please show your stack trace?

**Comment by psdantonio** [comment]
The intial problem was at line [335 ](https://github.com/nithinmurali/pygsheets/blob/master/pygsheets/cell.py#L335) but i see now that you updated so it now runs without the NoneValue error. thanks. 

as for my other formatting issue noted, i've attached a photo as sample (though i don't know if this deserves its own thread as the problem still exists after the above code fix). the gist of it is that while google sheets toolbar recognizes the formatting of a cell (eg as bold and font sz 10) the cell doesn't reflect the assigned formatting unless you click on it. 

here's the steps my code takes: create range....apply model format to range (background color and bold text)....write individual (text) values to cells. the same issue persists even if i work with individual cells instead of ranges.
![format_error](https://user-images.githubusercontent.com/13840284/27516443-d8e57a7a-5987-11e7-8534-b3ccecfea685.JPG)

**Comment by nithinmurali** [comment]
I am able to see the updates without double clicking. Is you pygsheets the latest version (1.1.2) ?

Try running this, and check if you can see the updates.
```
a = wks.cell("A5")
a.value = "test value"
a.set_text_format('bold', true)
a.color=(1.0,0,1.0,1.0)
```

**Comment by psdantonio** [comment]
i had been on 1.1.1 but just updated and am now getting an IOError from startup. as soon as i figure this problem out (perhaps something w/ my service_cred), i'll check to see if the formatting issue persists, and if so i'll make a new thread. thanks for the help and for pygsheets!
