### ISSUE TITLE
NaN written to google sheet on empty cell value

### ISSUE THREAD

**Issue by jainraje** [nithinmurali/pygsheets#92]
I noticed when reading an XLSX files to a DF and then writing that DF to google sheets using the set_dataframe method, NaN is written to cells of the google sheet if the cell value was empty. I'm thinking it would be best to just leave the cell empty as opposed to writing a NaN in the google sheet? If you agree, please update. thx.

**Comment by nithinmurali** [comment]
The NaN being empty is okay in your case because you are reading it from xlsx sheet, I think there might be other cases the NaN might need to be shown as is. So i have added an param to specify what value to replace NaN with.

**Comment by cdibble** [comment]
Thanks for adding this feature. The default value is not in the [documentation](https://pygsheets.readthedocs.io/en/stable/worksheet.html#pygsheets.Worksheet.set_dataframe) for `set_dataframe`, though the `nan` argument is specified in the docstrings. Just thought I'd point it out in case you were maintaining the documentation.

**Comment by parthagar** [comment]
As I understand, if I pass `nan=''` as a parameter to `set_dataframe`, then I see my Google Sheet having empty cells as they normally are.
@nithinmurali, can you confirm if `''` is the default value that gsheets uses for empty cells?

**Comment by nithinmurali** [comment]
@parthagar google sheets api considers empty string values to mark a cell empty.

**Comment by parthagar** [comment]
Thanks for confirming that @nithinmurali. I'll suggest to either make `''` as the default parameter or to add this to the documentation atleast, so that people looking for the most common/similar to pandas implementation [(to_csv)](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html) can easily understand this and don't need to experiment and verify.

**Comment by nithinmurali** [comment]
@parthagar Fair point. since changing defaults is a breaking change, I will update the docs.

**Comment by benlindsay** [comment]
Hi all! Glad to see an issue created for what I'm looking for. Since it looks like the docs haven't been updated yet, at least in the stable version, should this issue be reopened until they're updated? I'd like to see the docs ([here](https://pygsheets.readthedocs.io/en/stable/worksheet.html#pygsheets.Worksheet.set_dataframe)) show the default value of the `nan` argument (`nan="NaN"`) and have the argument description mention how to turn the `NaN`s into empty cells (set `nan=""` for null values to appear as empty cells).

Thanks for this awesome library!
